### ISSUE TITLE
git hub pages

### ISSUE THREAD

**Issue by mjn81** [Hosseinghadirzadeh/Simple-VisaCard#1]
create a github pages for it :\ .

**Comment by Hosseinghadirzadeh** [comment]
اینو دوسش نداشتم گفتی چطوری بزنم براش؟  Sent from Mail for Windows From: Mohammad.J.NajafiSent: Saturday, August 27, 2022 8:44 PMTo: Hosseinghadirzadeh/Simple-VisaCardCc: SubscribedSubject: [Hosseinghadirzadeh/Simple-VisaCard] git hub pages (Issue #1) create a github pages for it :\ .—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
